version: "3.8"

services:

  web:
    build: .
    command: gunicorn --bind 0.0.0.0:5000 app:app
    ports:
      - 5000:5000
    environment:
      - DB_NAME=football_teamdb
      - DB_USER=postgres
      - DB_PASSWORD=admin123
      - DB_HOST=pg
      - DB_PORT=5432
      - DATABASE=postgres
    depends_on:
      - pg
  pg:
      container_name: pg_container
      image: postgres:13.2-alpine
      restart: always
      environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: admin123
          POSTGRES_DB: football_teamdb                                             
          POSTGRES_HOST_AUTH_METHOD: trust
      ports:
          - "5432:5432"
      volumes:
          - ./data:/data
          - ./data/misc/django_init.sql:/docker-entrypoint-initdb.d/1-django-init.sql
          - pg_volume:/var/lib/postgresql/data
  pgadmin:
      container_name: pgadmin_container
      image: dpage/pgadmin4:5.2
      restart: always
      environment:
          PGADMIN_DEFAULT_EMAIL: admin@example.com
          PGADMIN_DEFAULT_PASSWORD: admin123
          PGADMIN_LISTEN_PORT: 5433
          PGADMIN_CONFIG_SERVER_MODE: "False"
          PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
      user: root
      ports:
          - "5433:5433"
      
      depends_on:

          - pg
      volumes:
          - pg_admin_v:/var/lib/pgadmin
          
 
volumes:
    pg_admin_v:
    pg_volume:
        driver: local  